### ISSUE TITLE
Architecture mismatch 

### ISSUE THREAD

**Issue by brutella** [oliverpool/kernel-rpi-os-32#4]
When I try to use this kernel with gokrazy by setting `KernelPackage` to `github.com/gokrazy-community/kernel-rpi-os-32/dist` in the config file, I get the following error.

```
target architecture "arm64" doesn't match the github.com/gokrazy-community/kernel-rpi-os-32/dist kernel type "arm"
```

Any ideas on how to get this fixed?

**Comment by oliverpool** [comment]
Hi @brutella, nice to see you here (I am a big fan of your work on homekit :heart: ).

Did you set `GOARCH=arm` when building?

**Comment by oliverpool** [comment]
I just saw https://github.com/gokrazy/gokrazy/issues/191 and https://github.com/gokrazy/tools/pull/54, which are causing this behavior.

Maybe the error message could be improved?

**Comment by brutella** [comment]
Prefixing the command `gok overwrite --full ...` with `GOARCH=arm` did fix the issue. Thanks.
