### ISSUE TITLE
Network failing on RPI1 and RPI Zero W, also no serial console

### ISSUE THREAD

**Issue by TinHead** [oliverpool/kernel-rpi-os-32#8]
Hello,

Not sure if this is a bug or not, is networking and serial console supposed to be working on these old devices?
I do get booting and HDMI framebuffer though nothing related to networking, being wifi or ethernet.

Also serial console does not seem to work either.

Cheers,
TH

**Comment by oliverpool** [comment]
I have a Raspberry Pi Model B (likely what you call `RPI1`) and it works flawlessly with Ethernet (it gets a DHCP lease from my router).

**Comment by oliverpool** [comment]
The serial console is disabled in https://github.com/gokrazy-community/kernel-rpi-os-32/blob/8047e65a8e8fcd861b02280b43b0c9d84db0d578/dist/config.txt#L3

**Comment by TinHead** [comment]
> I have a Raspberry Pi Model B (likely what you call `RPI1`) and it works flawlessly with Ethernet (it gets a DHCP lease from my router).

Yes that's the one forgot the naming scheme. OK thanks for the reply it's probably my mistake somewhere :) .
I'll give it another whirl tonight and get back at you.

**Comment by TinHead** [comment]
OK turns out it was just me newbie and that older devices have weird issues with my new wifi network. All good closing. 
Thanks!
